name: Post-Merge Workflow

on:
  push:
    branches:
      - prod

jobs:
  run-on-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Environment Information
        run: |
          echo "Merge into prod was successful!"
