name: Post-Merge Workflow

on:
  push:
    branches:
      - prod

jobs:
  run-on-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Git Config
        run: |
          git config user.name "${{ secrets.YUNSECODE_BOT_NAME }}"
          git config user.email "${{ secrets.YUNSECODE_BOT_EMAIL }}"

      - name: Version Bump and Push
        run: |
          # 예: 버전을 올리고 커밋하는 명령어 실행
          npm version patch -m "Upgrade to %s [skip ci]"
          git push --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
