name: Merge to Prod

on:
  push:
    branches:
      - prod

jobs:
  merge_to_prod:
    if: github.actor != 'yunsecode'
    runs-on: ubuntu-latest

    steps:
    - name: Check last committer
      run: |
        echo "PR merged to prod branch"
