name: Post-Merge Workflow

on:
  push:
    branches:
      - prod

jobs:
  run-on-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Git Config
        run: |
          git config user.name "${{ secrets.YUNSECODE_BOT_NAME }}"
          git config user.email "${{ secrets.YUNSECODE_BOT_EMAIL }}"

      - name: Version change
        run: |
          npm version patch
          git push --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.YUNSECODE_BOT_TOKEN }}
