name: Post-Merge Workflow

on:
  push:
    branches:
      - prod

jobs:
  run-on-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Scss Order version
        run: |
          run: npm version patch --no-git-tag-version

